### ISSUE TITLE
[Data Cleaning] MaxMind regions are sometimes just the cities

### ISSUE THREAD

**Issue by pbeshai** [bocoup/mlab-vis-pipeline#11]
"London, City of"  is the region name.
See:
![image](https://cloud.githubusercontent.com/assets/793847/18683045/a5fa999a-7f3c-11e6-87cf-584d8f507b4c.png)

**Comment by pbeshai** [comment]
So that is the region London, the city London is inside this region. The problem seems to stem from the fact that the `bocoup.location_region_codes` table has many cities as region names for the specified region codes in GB at least.

![image](https://cloud.githubusercontent.com/assets/793847/19700967/66d8f8fa-9ac7-11e6-82f2-97b851b86044.png)

**Comment by pbeshai** [comment]
We get our data from http://dev.maxmind.com/faq/how-do-i-convert-region-codes-to-names/. It's not clear how we can easily fix this. Do we just get rid of region codes and names for GB? I think we can just accept it for now.

**Comment by pbeshai** [comment]
Note that #31 adds in support for removing the region by setting the `new_region_code` to `null` in the location_cleaning table. London is in there as an example.

**Comment by pbeshai** [comment]
On further investigation, it seems that region codes are necessary for our system to work. So setting to null is not possible. Every city in the data currently has a region. If the region is wrong, one could possibly update the region code to another one or create a new region code then use the Location Names resolver part of the pipeline to resolve that region code to a new region name.

**Comment by vlandham** [comment]
peter fixed this with an additional table.
