### ISSUE TITLE
Test counts appear to be wrong for time series

### ISSUE THREAD

**Issue by iros** [bocoup/mlab-vis-pipeline#14]
Super low on country level:

http://client-dot-mlab-oti.appspot.com/compare/location?aggr=month&end=2016-10-01&selected=eufr_eude_naus

They appear to be fine for the hour data.

**Comment by iros** [comment]
![image](https://cloud.githubusercontent.com/assets/18690/18919775/5992294c-856d-11e6-94e5-dece0cf96813.png)

**Comment by vlandham** [comment]
This was corrected by removing time zone info from aggregations.
